[build]
  # This tells Netlify where the main project is located
  base = "product-recommendation"
  # This is the command to run *inside* the base directory
  command = "npm run build"
  # This is the folder the command produces, relative to the base directory
  publish = "product-recommendation/build"

# If you use React Router, add this for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
